### ISSUE TITLE
Wrong app hash calculated after node restart.

### ISSUE THREAD

**Issue by mrlp4** [cybercongress/go-cyber#453]
In approx. 20% cases when docker container being stopped, and then started back up wrong app hash being calculated, node crashing.

```bash
I[2020-01-30|16:05:52.869] Committed state                              module=state height=635569 txs=0 appHash=1898EBFDFCAF0B0380687A89280D703D88C31521769C0C8DBDA6857C2AF16643
I[2020-01-30|16:05:53.003] Executed block                               module=state height=635570 validTxs=0 invalidTxs=0
I[2020-01-30|16:05:53.024] Rank: data for gpu preparation               module=main time=21.248322ms
I[2020-01-30|16:05:53.026] Rank: gpu calculations                       module=main time=1.90216ms
I[2020-01-30|16:05:53.027] Rank constructing tree                       module=main time=869.223µs
I[2020-01-30|16:05:53.027] Rank calculated                              module=main time=24.215849ms links=611 cids=596 hash=de8040728e5ea009e86726bbee2308282bcca2f562ed9d4399e392c1deaaedb8
I[2020-01-30|16:05:53.059] Committed state                              module=state height=635570 txs=0 appHash=839B9BC0051D6FA268678964AC17EDE54A7FDCDD930D64C6D5565CF2993CDF19
panic: Failed to process committed block (635571:FDA2E8DEF9B1792C93C1A35FBBFC056002A73444B2CCF2214DC8898C9578B91C): Wrong Block.Header.AppHash.  Expected 839B9BC0051D6FA268678964AC17EDE54A7FDCDD930D64C6D5565CF2993CDF19, got 1898EBFDFCAF0B0380687A89280D703D88C31521769C0C8DBDA6857C2AF16643

goroutine 4038024 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000c921a0)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:344 +0x12ff
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:118 +0x84
```

**Comment by mrlp4** [comment]
Issue was submitted by 3 more times by independent people. Hash calculated incorrectly after container/node restart.

**Comment by mrlp4** [comment]
New issue catch. Node - Mars.
Commands sequence: 

```bash
docker stop euler-5
cp -r /euler-5/cyberd/data/ /media/mars/raid1/data.backups.euler5/04_02_2020/
docker start euler-5
```

Logs: 

```bash
root@mars:~# docker logs euler-5 --follow --tail 20
I[2020-02-04|08:55:53.339] Executed block                               module=state height=707840 validTxs=0 invalidTxs=0
I[2020-02-04|08:55:53.366] Committed state                              module=state height=707840 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:55:53.382] Rank: data for gpu preparation               module=main time=42.301204ms
I[2020-02-04|08:55:53.398] Rank: gpu calculations                       module=main time=16.491453ms
I[2020-02-04|08:55:53.399] Rank constructing tree                       module=main time=685.021µs
I[2020-02-04|08:55:53.399] Rank calculated                              module=main time=59.684628ms links=614 cids=600 hash=61274586122914ba62f422c95e82fca865a0a0cd35d86f336d4b93a858faf20c
I[2020-02-04|08:55:59.232] Executed block                               module=state height=707841 validTxs=0 invalidTxs=0
I[2020-02-04|08:55:59.256] Committed state                              module=state height=707841 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:04.652] Executed block                               module=state height=707842 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:04.677] Committed state                              module=state height=707842 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:10.325] Executed block                               module=state height=707843 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:10.351] Committed state                              module=state height=707843 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:15.829] Executed block                               module=state height=707844 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:15.859] Committed state                              module=state height=707844 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:21.554] Executed block                               module=state height=707845 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:21.582] Committed state                              module=state height=707845 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:21.591] Rank: data for gpu preparation               module=main time=36.306368ms
I[2020-02-04|08:56:21.607] Rank: gpu calculations                       module=main time=15.984518ms
I[2020-02-04|08:56:21.608] Rank constructing tree                       module=main time=635.017µs
I[2020-02-04|08:56:21.608] Rank calculated                              module=main time=53.115569ms links=614 cids=600 hash=61274586122914ba62f422c95e82fca865a0a0cd35d86f336d4b93a858faf20c
I[2020-02-04|08:56:26.899] Executed block                               module=state height=707846 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:26.923] Committed state                              module=state height=707846 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:32.568] Executed block                               module=state height=707847 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:32.593] Committed state                              module=state height=707847 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:38.224] Executed block                               module=state height=707848 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:38.254] Committed state                              module=state height=707848 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:43.835] Executed block                               module=state height=707849 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:43.860] Committed state                              module=state height=707849 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
root@mars:~# docker logs euler-5 --follow --tail 20
I[2020-02-04|08:56:15.829] Executed block                               module=state height=707844 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:15.859] Committed state                              module=state height=707844 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:21.554] Executed block                               module=state height=707845 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:21.582] Committed state                              module=state height=707845 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:21.591] Rank: data for gpu preparation               module=main time=36.306368ms
I[2020-02-04|08:56:21.607] Rank: gpu calculations                       module=main time=15.984518ms
I[2020-02-04|08:56:21.608] Rank constructing tree                       module=main time=635.017µs
I[2020-02-04|08:56:21.608] Rank calculated                              module=main time=53.115569ms links=614 cids=600 hash=61274586122914ba62f422c95e82fca865a0a0cd35d86f336d4b93a858faf20c
I[2020-02-04|08:56:26.899] Executed block                               module=state height=707846 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:26.923] Committed state                              module=state height=707846 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:32.568] Executed block                               module=state height=707847 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:32.593] Committed state                              module=state height=707847 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:38.224] Executed block                               module=state height=707848 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:38.254] Committed state                              module=state height=707848 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:56:43.835] Executed block                               module=state height=707849 validTxs=0 invalidTxs=0
I[2020-02-04|08:56:43.860] Committed state                              module=state height=707849 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|08:58:00.508] Starting application REST service (chain-id: "euler-5")... module=rest-server
I[2020-02-04|08:58:00.508] Starting RPC HTTP server on [::]:1317        module=rest-server
I[2020-02-04|08:58:00.511] starting ABCI with Tendermint                module=main
I[2020-02-04|08:58:00.858] Loading mem state                            module=main
I[2020-02-04|09:01:16.058] App loaded                                   module=main time=3m15.199363809s
I[2020-02-04|09:01:23.583] Executed block                               module=state height=707850 validTxs=0 invalidTxs=0
I[2020-02-04|09:01:23.612] Committed state                              module=state height=707850 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:01:23.619] Rank: data for gpu preparation               module=main time=35.567155ms
I[2020-02-04|09:01:23.729] Rank: gpu calculations                       module=main time=109.560933ms
I[2020-02-04|09:01:23.729] Rank constructing tree                       module=main time=579.712µs
I[2020-02-04|09:01:23.729] Rank calculated                              module=main time=145.906585ms links=614 cids=600 hash=0ede28bd3934061573b7471d7a9832f2e9fdc40982a55f98e03a4640a4dd0550
I[2020-02-04|09:01:23.751] Executed block                               module=state height=707851 validTxs=0 invalidTxs=0
I[2020-02-04|09:01:23.783] Committed state                              module=state height=707851 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:01:23.809] Executed block                               module=state height=707852 validTxs=0 invalidTxs=0
I[2020-02-04|09:01:23.843] Committed state                              module=state height=707852 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:01:23.881] Executed block                               module=state height=707853 validTxs=0 invalidTxs=0
I[2020-02-04|09:01:23.909] Committed state                              module=state height=707853 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:01:23.929] Executed block                               module=state height=707854 validTxs=0 invalidTxs=0
I[2020-02-04|09:01:23.959] Committed state                              module=state height=707854 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:01:24.104] Executed block                               module=state height=707855 validTxs=0 invalidTxs=0
I[2020-02-04|09:01:24.140] Committed state                              module=state height=707855 txs=0 appHash=C61F26787090CFB9D2F9FBD0170948054DE331EA815083EA0D8D864D79AC2EBB
I[2020-02-04|09:01:24.140] Rank: data for gpu preparation               module=main time=36.743021ms
I[2020-02-04|09:01:24.142] Rank: gpu calculations                       module=main time=1.807806ms
I[2020-02-04|09:01:24.143] Rank constructing tree                       module=main time=690.501µs
I[2020-02-04|09:01:24.143] Rank calculated                              module=main time=39.4916ms links=614 cids=600 hash=0ede28bd3934061573b7471d7a9832f2e9fdc40982a55f98e03a4640a4dd0550
panic: Failed to process committed block (707856:F3E49A161E44B03BA62E4DE69B928C5CF46CBD0B09F5EF57B012C458607EE104): Wrong Block.Header.AppHash.  Expected C61F26787090CFB9D2F9FBD0170948054DE331EA815083EA0D8D864D79AC2EBB, got A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7

goroutine 4038106 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000b1a4e0)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:344 +0x12ff
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:118 +0x84
```

**Comment by litvintech** [comment]
```
I[2020-02-04|09:13:20.037] Executed block                               module=state height=708027 validTxs=0 invalidTxs=0
I[2020-02-04|09:13:20.076] Committed state                              module=state height=708027 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:13:25.650] Executed block                               module=state height=708028 validTxs=0 invalidTxs=0
I[2020-02-04|09:13:25.693] Committed state                              module=state height=708028 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:13:31.532] Executed block                               module=state height=708029 validTxs=0 invalidTxs=0
I[2020-02-04|09:13:31.577] Committed state                              module=state height=708029 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:13:37.446] Executed block                               module=state height=708030 validTxs=0 invalidTxs=0
I[2020-02-04|09:13:37.480] Rank: data for gpu preparation               module=main time=33.148262ms
I[2020-02-04|09:13:37.484] Rank: gpu calculations                       module=main time=4.547255ms
I[2020-02-04|09:13:37.485] Rank constructing tree                       module=main time=645.537µs
I[2020-02-04|09:13:37.485] Rank calculated                              module=main time=38.542201ms links=614 cids=600 hash=61274586122914ba62f422c95e82fca865a0a0cd35d86f336d4b93a858faf20c
I[2020-02-04|09:13:37.490] Committed state                              module=state height=708030 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:16:08.132] starting ABCI with Tendermint                module=main
I[2020-02-04|09:16:08.154] Starting application REST service (chain-id: "euler-5")... module=rest-server
I[2020-02-04|09:16:08.154] Starting RPC HTTP server on [::]:1317        module=rest-server
I[2020-02-04|09:16:08.364] Loading mem state                            module=main
I[2020-02-04|09:19:33.101] App loaded                                   module=main time=3m24.736492189s
I[2020-02-04|09:19:34.669] Rank: data for gpu preparation               module=main time=32.297668ms
I[2020-02-04|09:19:34.815] Rank: gpu calculations                       module=main time=146.106699ms
I[2020-02-04|09:19:34.816] Rank constructing tree                       module=main time=734.192µs
I[2020-02-04|09:19:34.816] Rank calculated                              module=main time=179.399737ms links=614 cids=600 hash=0ede28bd3934061573b7471d7a9832f2e9fdc40982a55f98e03a4640a4dd0550
I[2020-02-04|09:19:40.601] Executed block                               module=state height=708031 validTxs=0 invalidTxs=0
I[2020-02-04|09:19:40.643] Committed state                              module=state height=708031 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:19:40.695] Executed block                               module=state height=708032 validTxs=0 invalidTxs=0
I[2020-02-04|09:19:40.757] Committed state                              module=state height=708032 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:19:40.811] Executed block                               module=state height=708033 validTxs=0 invalidTxs=0
I[2020-02-04|09:19:40.860] Committed state                              module=state height=708033 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:19:40.902] Executed block                               module=state height=708034 validTxs=0 invalidTxs=0
I[2020-02-04|09:19:40.964] Committed state                              module=state height=708034 txs=0 appHash=A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7
I[2020-02-04|09:19:41.145] Executed block                               module=state height=708035 validTxs=0 invalidTxs=0
I[2020-02-04|09:19:41.179] Rank: data for gpu preparation               module=main time=33.731093ms
I[2020-02-04|09:19:41.181] Rank: gpu calculations                       module=main time=1.839105ms
I[2020-02-04|09:19:41.181] Rank constructing tree                       module=main time=656.584µs
I[2020-02-04|09:19:41.181] Rank calculated                              module=main time=36.417249ms links=614 cids=600 hash=0ede28bd3934061573b7471d7a9832f2e9fdc40982a55f98e03a4640a4dd0550
I[2020-02-04|09:19:41.187] Committed state                              module=state height=708035 txs=0 appHash=C61F26787090CFB9D2F9FBD0170948054DE331EA815083EA0D8D864D79AC2EBB
panic: Failed to process committed block (708036:FE50C32C7606B813E1EAD38AB06AB8444BCA0FC39AE510A8F93BE6659D66E7D8): Wrong Block.Header.AppHash.  Expected C61F26787090CFB9D2F9FBD0170948054DE331EA815083EA0D8D864D79AC2EBB, got A9E64B435B8DDD16C3BA9E043313865FC1BE552E362DB34180FC53A5858BD9E7

goroutine 4038045 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00c6c01a0)
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:344 +0x12ff
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:118 +0x84
```

**Comment by serejandmyself** [comment]
https://github.com/tendermint/tendermint/issues/4036

**Comment by serejandmyself** [comment]
Got a similar bug whilst trying to sync a new node

```
B2DE8B86AA19A93


I[2020-02-05|16:12:38.997] Executed block                               module=state height=141020 validTxs=0 invalidTxs=0

I[2020-02-05|16:12:39.022] Rank: data for gpu preparation               module=main time=25.177017ms

I[2020-02-05|16:12:39.023] Rank: gpu calculations                       module=main time=1.59113ms

I[2020-02-05|16:12:39.024] Rank constructing tree                       module=main time=190.05µs

I[2020-02-05|16:12:39.024] Rank calculated                              module=main time=27.052547ms links=183 cids=208 hash=f0d4c6189809eb6a9a7cf0ab660dd76c1788c79b321cf22a38896628034cd3f1

I[2020-02-05|16:12:39.038] Committed state                              module=state height=141020 txs=0 appHash=1FF8BB7C56AAB736E97F20FBA4AC63C871F52463C35023529B2DE8B86AA19A93

I[2020-02-05|16:12:39.067] Executed block                               module=state height=141021 validTxs=0 invalidTxs=0

I[2020-02-05|16:12:39.108] Committed state                              module=state height=141021 txs=0 appHash=1FF8BB7C56AAB736E97F20FBA4AC63C871F52463C35023529B2DE8B86AA19A93

I[2020-02-05|16:12:39.149] Executed block                               module=state height=141022 validTxs=0 invalidTxs=0

panic: leveldb/table: corruption on data-block (pos=535796): checksum mismatch, want=0x573962de got=0x86239606 [file=295257.ldb]

goroutine 2019026 [running]:

github.com/tendermint/tm-db.(*goLevelDBBatch).Write(0xc01536ea30)

/root/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/go_level_db.go:172 +0x7f

github.com/tendermint/tm-db.prefixBatch.Write(...)

/root/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/prefix_db.go:244

github.com/tendermint/iavl.(*nodeDB).Commit(0xc000b60e10)

/root/go/pkg/mod/github.com/tendermint/iavl@v0.12.4/nodedb.go:332 +0x82

github.com/tendermint/iavl.(*MutableTree).SaveVersion(0xc000d49860, 0x3, 0x0, 0x108da00, 0xc000d96b38, 0xc000d48a20, 0xc000d96bb8)

/root/go/pkg/mod/github.com/tendermint/iavl@v0.12.4/mutable_tree.go:415 +0xef

github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc000d5cfe0, 0xc000d48a20, 0xc000ce88a0, 0xc000cbaa80, 0x0)

/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/store/iavl/store.go:105 +0x37

github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0x226de, 0xc000d48a20, 0x8020103, 0x1, 0xffffffffffffffff, 0xc000ce89b8)

/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/store/rootmulti/store.go:528 +0x165

github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0000ec180, 0x0, 0x0, 0x0, 0x0)

/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/store/rootmulti/store.go:203 +0x68

github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc000d92120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/baseapp/baseapp.go:1020 +0x1ad

github.com/cybercongress/cyberd/app.(*CyberdApp).Commit(0xc000d53c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/sources/app/app.go:557 +0x88

github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000ae51a0, 0x0, 0x0, 0x0)

/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/abci/client/local_client.go:215 +0xcf

github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc0004c5100, 0x0, 0x0, 0xf)

/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/proxy/app_conn.go:81 +0x33

github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc054e19a40, 0xa, 0x0, 0xc026de70d0, 0x6, 0xc026de70f0, 0x7, 0x226de, 0x17c, 0xc0108dd520, ...)

/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/state/execution.go:212 +0x224

github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc054e19a40, 0xa, 0x0, 0xc026de70d0, 0x6, 0xc026de70f0, 0x7, 0x226de, 0x17c, 0xc0108dd520, ...)

/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/state/execution.go:166 +0x625

github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000d4dba0)

/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:341 +0x96a

created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart

/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.8/blockchain/v0/reactor.go:118 +0x84
```

**Comment by litvintech** [comment]
We upgraded links storage from our custom one to sdk's in ongoing euler-6 (branch 0.1.6) 
Going to live this issue for a time before we successfully pass all tests
