### ISSUE TITLE
Can't fund community pool

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/go-cyber#575]
I'm trying to return 732 256 061 022 EUL tokens from the evangelist coordinator account, to the community pool. 

This is the transaction I'm using:

```
cyberdcli tx distribution fund-community-pool 3eul --chain-id euler-6 --from MYADDRESS
```

(3 euls is just a test transaction)

This is the trace I'm getting:

```
panic: Cannot encode unregistered concrete type types.MsgFundCommunityPool.

goroutine 1 [running]:
github.com/tendermint/go-amino.(*Codec).MustMarshalJSON(...)
  /root/go/pkg/mod/github.com/tendermint/go-amino@v0.15.1/amino.go:406
github.com/cosmos/cosmos-sdk/x/auth/client/utils.CompleteAndBroadcastTxCLI(0xc00016bb90, 0x14b2460, 0xc000345360, 0xf6725, 0x5b, 0x30d40, 0x3ff0000000000000, 0x0, 0x7fff5375d0be, 0x7, ...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/x/auth/client/utils/tx.go:83 +0xba1
github.com/cosmos/cosmos-sdk/x/auth/client/utils.GenerateOrBroadcastMsgs(0xc000bbe460, 0x14, 0x20, 0x14b7d20, 0xc000bc16e0, 0x7fff5375d0be, 0x7, 0x0, 0x0, 0x147d4a0, ...)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/x/auth/client/utils/tx.go:40 +0x15c
github.com/cosmos/cosmos-sdk/x/distribution/client/cli.GetCmdFundCommunityPool.func1(0xc000b838c0, 0xc000345310, 0x1, 0x5, 0x0, 0x0)
  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/x/distribution/client/cli/tx.go:297 +0x403
github.com/spf13/cobra.(*Command).execute(0xc000b838c0, 0xc0003452c0, 0x5, 0x5, 0xc000b838c0, 0xc0003452c0)
  /root/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e3340, 0x8957f0, 0xc0000e3340, 0x1129e2f)
  /root/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
  /root/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000e3340, 0x132ad70, 0x5, 0xc000b6c1a0)
  /root/go/pkg/mod/github.com/tendermint/tendermint@v0.33.3/libs/cli/setup.go:89 +0x3c
main.main()
  /root/go-cyber/cmd/cyberdcli/main.go:71 +0x3bf
```

**Comment by litvintech** [comment]
There was the bug in cosmos-sdk, resolved in stargate
